DEBUG = False
SECRET_KEY = '?\xbf,\xb4\x8d\xa3"<\x9c\xb0@\x0f5\xab,w\xee\x8d$0\x13\x8b83'

AWS_ACCESS_KEY_ID = 'YOUR_AWS_ACCESS_KEY_ID'
AWS_SECRET_ACCESS_KEY = 'YOUR_AWS_SECRET_ACCESS_KEY'
AWS_BUCKET = 'YOUR_AWS_BUCKET'

LYDON_WORKING_DIR = 'YOUR_WORKING_DIRECTORY'
LYDON_CACHE_TIMEOUT = 60*60*24*365*10  # 10 years